<a href="https://colab.research.google.com/github/ameympatil/NLP/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 15 kB/s 
     |████████████████████████████████| 1.7 MB 55.0 MB/s 
     |████████████████████████████████| 5.9 MB 47.5 MB/s 
     |████████████████████████████████| 438 kB 70.3 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully u

In [3]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[326, 193, 37, 169], [326, 193, 37, 387], [326, 7, 37, 231], [278, 372, 257, 297, 20], [278, 372, 257, 297, 212], [97, 326, 465, 37, 304], [390, 173, 131, 297]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 326 193  37 169]
 [  0   0   0   0 326 193  37 387]
 [  0   0   0   0 326   7  37 231]
 [  0   0   0 278 372 257 297  20]
 [  0   0   0 278 372 257 297 212]
 [  0   0   0  97 326 465  37 304]
 [  0   0   0   0 390 173 131 297]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 326, 193,  37, 169], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[-0.03283658,  0.0392232 ,  0.03144247, -0.01047589,  0.009     ,
         0.04156829, -0.01806079, -0.02673535,  0.03109298, -0.0045856 ],
       [-0.03283658,  0.0392232 ,  0.03144247, -0.01047589,  0.009     ,
         0.04156829, -0.01806079, -0.02673535,  0.03109298, -0.0045856 ],
       [-0.03283658,  0.0392232 ,  0.03144247, -0.01047589,  0.009     ,
         0.04156829, -0.01806079, -0.02673535,  0.03109298, -0.0045856 ],
       [-0.03283658,  0.0392232 ,  0.03144247, -0.01047589,  0.009     ,
         0.04156829, -0.01806079, -0.02673535,  0.03109298, -0.0045856 ],
       [ 0.03361282, -0.00091664,  0.03515153, -0.01352024, -0.01873715,
         0.0455972 ,  0.03006412,  0.03376487,  0.0109804 ,  0.03723573],
       [-0.04932937, -0.01210111, -0.02027177,  0.02392943, -0.00010809,
        -0.00299164,  0.01843384, -0.03982387,  0.01117023,  0.00627226],
       [ 0.00403009, -0.03583927, -0.02085699, -0.00455619, -0.0301855 ,
         0.03096074, -0.04436474, -0.02199133

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[-3.28365788e-02  3.92231978e-02  3.14424671e-02 -1.04758851e-02
    9.00000334e-03  4.15682904e-02 -1.80607922e-02 -2.67353542e-02
    3.10929753e-02 -4.58560139e-03]
  [-3.28365788e-02  3.92231978e-02  3.14424671e-02 -1.04758851e-02
    9.00000334e-03  4.15682904e-02 -1.80607922e-02 -2.67353542e-02
    3.10929753e-02 -4.58560139e-03]
  [-3.28365788e-02  3.92231978e-02  3.14424671e-02 -1.04758851e-02
    9.00000334e-03  4.15682904e-02 -1.80607922e-02 -2.67353542e-02
    3.10929753e-02 -4.58560139e-03]
  [-3.28365788e-02  3.92231978e-02  3.14424671e-02 -1.04758851e-02
    9.00000334e-03  4.15682904e-02 -1.80607922e-02 -2.67353542e-02
    3.10929753e-02 -4.58560139e-03]
  [ 3.36128213e-02 -9.16637480e-04  3.51515301e-02 -1.35202408e-02
   -1.87371485e-02  4.55971994e-02  3.00641172e-02  3.37648727e-02
    1.09804049e-02  3.72357257e-02]
  [-4.93293665e-02 -1.21011138e-02 -2.02717669e-02  2.39294283e-02
   -1.08085573e-04 -2.99163908e

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 326, 193,  37, 169], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.03283658  0.0392232   0.03144247 -0.01047589  0.009       0.04156829
  -0.01806079 -0.02673535  0.03109298 -0.0045856 ]
 [-0.03283658  0.0392232   0.03144247 -0.01047589  0.009       0.04156829
  -0.01806079 -0.02673535  0.03109298 -0.0045856 ]
 [-0.03283658  0.0392232   0.03144247 -0.01047589  0.009       0.04156829
  -0.01806079 -0.02673535  0.03109298 -0.0045856 ]
 [-0.03283658  0.0392232   0.03144247 -0.01047589  0.009       0.04156829
  -0.01806079 -0.02673535  0.03109298 -0.0045856 ]
 [ 0.03361282 -0.00091664  0.03515153 -0.01352024 -0.01873715  0.0455972
   0.03006412  0.03376487  0.0109804   0.03723573]
 [-0.04932937 -0.01210111 -0.02027177  0.02392943 -0.00010809 -0.00299164
   0.01843384 -0.03982387  0.01117023  0.00627226]
 [ 0.00403009 -0.03583927 -0.02085699 -0.00455619 -0.0301855   0.03096074
  -0.04436474 -0.02199133 -0.02890624 -0.02976973]
 [ 0.04197457 -0.03379529  0.0295797   0.02699618 -0.04487772  0.01458491


In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [21]:
voc_size=1000

In [22]:
#OHE
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[97, 993, 73, 104, 83, 480], [309, 111, 73, 40, 898, 816], [744, 219, 807, 466], [97, 265, 73, 242, 97, 693], [414, 577, 321, 73, 40, 898, 816], [514, 73, 40, 898, 977, 453]]


In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [24]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[  0   0  97 993  73 104  83 480]
 [  0   0 309 111  73  40 898 816]
 [  0   0   0   0 744 219 807 466]
 [  0   0  97 265  73 242  97 693]
 [  0 414 577 321  73  40 898 816]
 [  0   0 514  73  40 898 977 453]]


In [25]:
## 10 feature dimesnions
dim=10


In [26]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
embedded_docs[0]

array([  0,   0,  97, 993,  73, 104,  83, 480], dtype=int32)

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 70ms/step


array([[ 4.25562374e-02, -1.14289038e-02, -5.10170311e-03,
         2.16388442e-02, -2.88745891e-02, -2.46692188e-02,
         1.07342824e-02, -3.14458460e-03, -4.14179452e-02,
        -1.55724287e-02],
       [ 4.25562374e-02, -1.14289038e-02, -5.10170311e-03,
         2.16388442e-02, -2.88745891e-02, -2.46692188e-02,
         1.07342824e-02, -3.14458460e-03, -4.14179452e-02,
        -1.55724287e-02],
       [ 2.67691128e-02, -3.97337601e-03, -4.84623760e-03,
        -1.93629395e-02, -4.02806029e-02,  1.93106048e-02,
        -3.17760333e-02,  1.34107806e-02, -3.33673246e-02,
        -4.78095412e-02],
       [-3.47192399e-02, -1.68869123e-02, -2.20253710e-02,
        -3.63449082e-02, -1.60694122e-02,  1.52031519e-02,
        -3.64284888e-02, -2.82433517e-02,  4.97435443e-02,
         4.62707765e-02],
       [ 3.17614786e-02,  1.16852410e-02, -1.49835236e-02,
         4.72890772e-02, -4.43632863e-02, -4.12946120e-02,
         3.91481407e-02,  2.82489397e-02,  4.88573425e-02,
         3.

In [30]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 53ms/step
[[[ 4.25562374e-02 -1.14289038e-02 -5.10170311e-03  2.16388442e-02
   -2.88745891e-02 -2.46692188e-02  1.07342824e-02 -3.14458460e-03
   -4.14179452e-02 -1.55724287e-02]
  [ 4.25562374e-02 -1.14289038e-02 -5.10170311e-03  2.16388442e-02
   -2.88745891e-02 -2.46692188e-02  1.07342824e-02 -3.14458460e-03
   -4.14179452e-02 -1.55724287e-02]
  [ 2.67691128e-02 -3.97337601e-03 -4.84623760e-03 -1.93629395e-02
   -4.02806029e-02  1.93106048e-02 -3.17760333e-02  1.34107806e-02
   -3.33673246e-02 -4.78095412e-02]
  [-3.47192399e-02 -1.68869123e-02 -2.20253710e-02 -3.63449082e-02
   -1.60694122e-02  1.52031519e-02 -3.64284888e-02 -2.82433517e-02
    4.97435443e-02  4.62707765e-02]
  [ 3.17614786e-02  1.16852410e-02 -1.49835236e-02  4.72890772e-02
   -4.43632863e-02 -4.12946120e-02  3.91481407e-02  2.82489397e-02
    4.88573425e-02  3.52644213e-02]
  [ 3.74058634e-03 -3.23574767e-02  3.40775885e-02 -8.14614445e-03
    1.85784586e-02 -3.74525785e